export enum Category {
    General_Knowledge = "General Knowledge",
    Entertainment_Books = "Entertainment: Books",
    Entertainment_Film ="Entertainment: Film",
    Entertainment_Music ="Entertainment: Music",
    Entertainment_MusicalsTheatres ="Entertainment: Musicals & Theatres",
    Entertainment_Television ="Entertainment: Television",
    Entertainment_VideoGames ="Entertainment: Video Games",
    Entertainment_BoardGames ="Entertainment: Board Games",
    ScienceNature = "Science & Nature",
    Science_Computers = "Science: Computers",
    Science_Mathematics = "Science: Mathematics",
    Mythology = "Mythology",
    Sports = "Sports",
    Geography = "Geography",
    History = "History",
    Politics = "Politics",
    Art = "Art",
    Celebrities = "Celebrities",
    Animals = "Animals",
    Vehicles = "Vehicles",
    Entertainment_Comics ="Entertainment: Comics",
    Science_Gadgets = "Science: Gadgets",
    Entertainment_JapaneseAnimeManga ="Entertainment: Japanese Anime & Manga",
    Entertainment_CartoonsAnimations = "Entertainment: Cartoons & Animations",
}